// <auto-generated />
namespace Concordia42.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedName));
        
        string IMigrationMetadata.Id
        {
            get { return "201503121802088_addedName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
